#!/bin/bash
#
# rsync-lupin-mobile.sh - Rsync mirror script for Lupin Mobile (Flutter) sync
#
# Purpose: Sync Lupin Mobile Flutter project from network mount (Samba) to local
#          build directory for fast incremental builds on the Mac laptop.
#
# This script is written to the dev server but EXECUTED ON THE LAPTOP via the
# SMB-mounted path (/Volumes/data/...). The laptop has Flutter + Android SDK;
# the dev server does not.
#
# Usage:
#   ./rsync-lupin-mobile.sh                             # Dry-run with defaults
#   ./rsync-lupin-mobile.sh --write                     # Write with defaults + confirmation
#   ./rsync-lupin-mobile.sh --write --yes               # Write + auto-approve
#   ./rsync-lupin-mobile.sh /custom/source /custom/tgt  # Custom paths, dry-run
#
# Default Paths:
#   Source: /Volumes/data/include/www.deepily.ai/projects/lupin/src/lupin-mobile/
#   Target: ~/Projects/lupin-mobile
#
# Modeled on rsync-kotlin-java-client.sh from the Gemini project.
#

set -e

# ============================================================================
# Help
# ============================================================================

show_help() {
    cat << 'EOF'
rsync-lupin-mobile.sh - Rsync mirror script for Lupin Mobile Flutter project

USAGE:
    ./rsync-lupin-mobile.sh [OPTIONS] [SOURCE] [TARGET]

OPTIONS:
    --write         Enable write mode (actually sync files, requires confirmation)
    --yes, -y       Skip confirmation prompt in write mode (auto-approve)
    --help, -h      Show this help

DEFAULT PATHS:
    SOURCE: /Volumes/data/include/www.deepily.ai/projects/lupin/src/lupin-mobile/
    TARGET: ~/Projects/lupin-mobile

MODES:
    DRY-RUN (default)   Preview changes without modifying files
    WRITE (--write)     Actually sync files (prompts for confirmation)

EXCLUSIONS:
    Dart/Flutter artifacts:
      .dart_tool/                 (dart-tool cache, regenerated by pub get)
      build/                      (build outputs, APKs)
      .flutter-plugins-dependencies  (laptop-specific)
      ios/Flutter/ephemeral/      (generated Flutter iOS helpers)
      ios/Runner/GeneratedPluginRegistrant.m  (auto-regenerated)

    Vendored SDK:
      flutter/                    (the in-repo Flutter SDK — laptop has its own)

    IDE & OS:
      .idea/, .vscode/, *.iml, .DS_Store

    Build metadata:
      android/local.properties   (per-machine Flutter SDK path)

    Version control:
      .git/                       (do not sync git state)

SAFETY:
    - Default mode is DRY-RUN (no changes)
    - Write mode requires explicit "y" confirmation
    - Mirror mode with --delete (removes files in target not in source)
EOF
    exit 0
}

# ============================================================================
# Defaults
# ============================================================================

DEFAULT_SOURCE="/Volumes/data/include/www.deepily.ai/projects/lupin/src/lupin-mobile/"
DEFAULT_TARGET="~/Projects/lupin-mobile"

# ============================================================================
# Parse arguments (any order)
# ============================================================================

WRITE_MODE=false
AUTO_APPROVE=false
SOURCE=""
TARGET=""

for arg in "$@"; do
    case "$arg" in
        --help|-h)    show_help ;;
        --write)      WRITE_MODE=true ;;
        --yes|-y)     AUTO_APPROVE=true ;;
        *)
            if [ -z "$SOURCE" ]; then
                SOURCE="$arg"
            elif [ -z "$TARGET" ]; then
                TARGET="$arg"
            fi
            ;;
    esac
done

[ -z "$SOURCE" ] && SOURCE="$DEFAULT_SOURCE"
[ -z "$TARGET" ] && TARGET="$DEFAULT_TARGET"

# Expand ~ in both paths
SOURCE="${SOURCE/#\~/$HOME}"
TARGET="${TARGET/#\~/$HOME}"

# ============================================================================
# Validation
# ============================================================================

if [ ! -d "$SOURCE" ]; then
    echo ""
    echo "❌ ERROR: Source directory does not exist:"
    echo "   $SOURCE"
    echo ""
    if [[ "$SOURCE" == /Volumes/* ]]; then
        echo "   Tip: Make sure the SMB mount is connected (Finder → Go → Connect to Server)."
    fi
    echo ""
    exit 1
fi

if [ ! -r "$SOURCE" ]; then
    echo "❌ ERROR: Source not readable: $SOURCE"
    exit 1
fi

TARGET_PARENT=$(dirname "$TARGET")
if [ ! -d "$TARGET_PARENT" ]; then
    echo "❌ ERROR: Target parent does not exist: $TARGET_PARENT"
    echo "   Create it: mkdir -p \"$TARGET_PARENT\""
    exit 1
fi

if [ ! -w "$TARGET_PARENT" ]; then
    echo "❌ ERROR: Target parent not writable: $TARGET_PARENT"
    exit 1
fi

if [ -d "$TARGET" ] && [ ! -w "$TARGET" ]; then
    echo "❌ ERROR: Target exists but not writable: $TARGET"
    exit 1
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "  Rsync Mirror: Lupin Mobile (Flutter) Sync"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "Source: $SOURCE"
echo "Target: $TARGET"
echo ""

if [ "$WRITE_MODE" = true ]; then
    echo "Mode:   🔴 WRITE MODE (will modify target directory)"
else
    echo "Mode:   🔵 DRY-RUN (preview only, no changes)"
fi

echo ""
echo "Excludes:"
echo "  - .dart_tool/, build/, .flutter-plugins-dependencies"
echo "  - flutter/ (vendored SDK), ios/Flutter/ephemeral/"
echo "  - .idea/, .vscode/, *.iml, .DS_Store"
echo "  - android/local.properties, .git/"
echo ""
echo "──────────────────────────────────────────────────────────────────────"

# ============================================================================
# Confirmation (write mode)
# ============================================================================

if [ "$WRITE_MODE" = true ]; then
    echo ""
    echo "⚠️  WARNING: This will overwrite/delete files in the target directory!"
    echo ""

    if [ "$AUTO_APPROVE" = true ]; then
        echo "✅ Auto-approved (--yes). Starting sync..."
    else
        read -p "Overwrite target directory? [y/N]: " -r CONFIRM
        echo ""
        CONFIRM=$(echo "$CONFIRM" | tr '[:upper:]' '[:lower:]')
        if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "yes" ]; then
            echo "❌ Cancelled."
            exit 0
        fi
        echo "✅ Confirmed. Starting sync..."
    fi
    echo ""
fi

# ============================================================================
# Rsync command
# ============================================================================

RSYNC_OPTS=(
    -av
    --delete
    --exclude='.dart_tool/'
    --exclude='build/'
    --exclude='.flutter-plugins-dependencies'
    --exclude='ios/Flutter/ephemeral/'
    --exclude='ios/Runner/GeneratedPluginRegistrant.m'
    --exclude='flutter/'
    --exclude='.idea/'
    --exclude='.vscode/'
    --exclude='*.iml'
    --exclude='.DS_Store'
    --exclude='android/local.properties'
    --exclude='.git/'
)

if [ "$WRITE_MODE" = false ]; then
    RSYNC_OPTS+=(--dry-run)
fi

# ============================================================================
# Execute
# ============================================================================

echo "Executing rsync..."
echo ""
echo "Command:"
echo "  rsync ${RSYNC_OPTS[*]} \"$SOURCE\" \"$TARGET\""
echo ""
echo "──────────────────────────────────────────────────────────────────────"
echo ""

if [ "$WRITE_MODE" = true ] && [ ! -d "$TARGET" ]; then
    mkdir -p "$TARGET"
fi

rsync "${RSYNC_OPTS[@]}" "$SOURCE" "$TARGET"
RSYNC_EXIT_CODE=$?

# ============================================================================
# Summary
# ============================================================================

echo ""
echo "──────────────────────────────────────────────────────────────────────"
echo ""

if [ $RSYNC_EXIT_CODE -eq 0 ]; then
    if [ "$WRITE_MODE" = true ]; then
        echo "✅ Sync completed successfully!"
        echo ""
        echo "Target: $TARGET"
        echo ""
        echo "Next steps:"
        echo "  1. cd $TARGET"
        echo "  2. flutter pub get"
        echo "  3. flutter build apk --debug"
    else
        echo "✅ Dry-run completed successfully!"
        echo ""
        echo "To actually sync:  $0 --write --yes"
    fi
else
    echo "❌ Rsync failed (exit $RSYNC_EXIT_CODE)"
    exit $RSYNC_EXIT_CODE
fi

echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo ""
