// Mocks generated by Mockito 5.4.6 from annotations
// in lupin_mobile/test/core/cache/voice_recording_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:lupin_mobile/core/cache/cache_manager.dart' as _i2;
import 'package:lupin_mobile/core/cache/cache_policy.dart' as _i4;
import 'package:lupin_mobile/core/cache/offline_manager.dart' as _i3;
import 'package:lupin_mobile/core/storage/storage_manager.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCacheManager_0<T1> extends _i1.SmartFake
    implements _i2.CacheManager<T1> {
  _FakeCacheManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOfflineStats_1 extends _i1.SmartFake implements _i3.OfflineStats {
  _FakeOfflineStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachePolicy_2 extends _i1.SmartFake implements _i4.CachePolicy {
  _FakeCachePolicy_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheStats_3 extends _i1.SmartFake implements _i2.CacheStats {
  _FakeCacheStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStorageStats_4 extends _i1.SmartFake implements _i5.StorageStats {
  _FakeStorageStats_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [OfflineManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineManager extends _i1.Mock implements _i3.OfflineManager {
  MockOfflineManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  bool get isOffline => (super.noSuchMethod(
        Invocation.getter(#isOffline),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i3.OfflineEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i6.Stream<_i3.OfflineEvent>.empty(),
      ) as _i6.Stream<_i3.OfflineEvent>);

  @override
  _i2.CacheManager<T> getCacheManager<T>({
    required String? cacheKey,
    required Map<String, dynamic> Function(T)? toJson,
    required T Function(Map<String, dynamic>)? fromJson,
    _i4.CachePolicy? policy = _i4.CachePolicy.defaultPolicy,
    int Function(T)? calculateSize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCacheManager,
          [],
          {
            #cacheKey: cacheKey,
            #toJson: toJson,
            #fromJson: fromJson,
            #policy: policy,
            #calculateSize: calculateSize,
          },
        ),
        returnValue: _FakeCacheManager_0<T>(
          this,
          Invocation.method(
            #getCacheManager,
            [],
            {
              #cacheKey: cacheKey,
              #toJson: toJson,
              #fromJson: fromJson,
              #policy: policy,
              #calculateSize: calculateSize,
            },
          ),
        ),
      ) as _i2.CacheManager<T>);

  @override
  _i6.Future<void> cacheForOffline<T>(
    String? cacheKey,
    String? itemKey,
    T? data, {
    Map<String, dynamic>? metadata,
    _i4.CachePolicy? policy,
    required Map<String, dynamic> Function(T)? toJson,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForOffline,
          [
            cacheKey,
            itemKey,
            data,
          ],
          {
            #metadata: metadata,
            #policy: policy,
            #toJson: toJson,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<T?> getCachedData<T>(
    String? cacheKey,
    String? itemKey, {
    required Map<String, dynamic> Function(T)? toJson,
    required T Function(Map<String, dynamic>)? fromJson,
    _i4.CachePolicy? policy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedData,
          [
            cacheKey,
            itemKey,
          ],
          {
            #toJson: toJson,
            #fromJson: fromJson,
            #policy: policy,
          },
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<void> queueRequest(
    String? requestKey,
    Map<String, dynamic>? requestData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueRequest,
          [
            requestKey,
            requestData,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeFromQueue(String? requestKey) => (super.noSuchMethod(
        Invocation.method(
          #removeFromQueue,
          [requestKey],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i3.QueuedRequest> getQueuedRequests() => (super.noSuchMethod(
        Invocation.method(
          #getQueuedRequests,
          [],
        ),
        returnValue: <_i3.QueuedRequest>[],
      ) as List<_i3.QueuedRequest>);

  @override
  _i6.Future<void> processQueuedRequests() => (super.noSuchMethod(
        Invocation.method(
          #processQueuedRequests,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> enableOfflineMode() => (super.noSuchMethod(
        Invocation.method(
          #enableOfflineMode,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> disableOfflineMode() => (super.noSuchMethod(
        Invocation.method(
          #disableOfflineMode,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.OfflineStats> getOfflineStats() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineStats,
          [],
        ),
        returnValue: _i6.Future<_i3.OfflineStats>.value(_FakeOfflineStats_1(
          this,
          Invocation.method(
            #getOfflineStats,
            [],
          ),
        )),
      ) as _i6.Future<_i3.OfflineStats>);

  @override
  _i6.Future<void> clearOfflineData() => (super.noSuchMethod(
        Invocation.method(
          #clearOfflineData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheManager<T> extends _i1.Mock implements _i2.CacheManager<T> {
  MockCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get cacheKey => (super.noSuchMethod(
        Invocation.getter(#cacheKey),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#cacheKey),
        ),
      ) as String);

  @override
  _i4.CachePolicy get policy => (super.noSuchMethod(
        Invocation.getter(#policy),
        returnValue: _FakeCachePolicy_2(
          this,
          Invocation.getter(#policy),
        ),
      ) as _i4.CachePolicy);

  @override
  Map<String, dynamic> Function(T) get toJson => (super.noSuchMethod(
        Invocation.getter(#toJson),
        returnValue: (T __p0) => <String, dynamic>{},
      ) as Map<String, dynamic> Function(T));

  @override
  T Function(Map<String, dynamic>) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (Map<String, dynamic> __p0) => _i7.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as T Function(Map<String, dynamic>));

  @override
  _i6.Stream<_i2.CacheEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i6.Stream<_i2.CacheEvent>.empty(),
      ) as _i6.Stream<_i2.CacheEvent>);

  @override
  _i6.Future<T?> get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i6.Future<T?>.value(),
      ) as _i6.Future<T?>);

  @override
  _i6.Future<void> put(
    String? key,
    T? value, {
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
          {#metadata: metadata},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i2.CacheStats getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _FakeCacheStats_3(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        ),
      ) as _i2.CacheStats);

  @override
  _i6.Future<void> cleanup() => (super.noSuchMethod(
        Invocation.method(
          #cleanup,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageManager extends _i1.Mock implements _i5.StorageManager {
  MockStorageManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  _i6.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  _i6.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  _i6.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  _i6.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i6.Future<bool> setJson(
    String? key,
    Map<String, dynamic>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setJson,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  Map<String, dynamic>? getJson(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getJson,
        [key],
      )) as Map<String, dynamic>?);

  @override
  _i6.Future<bool> setJsonList(
    String? key,
    List<Map<String, dynamic>>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setJsonList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  List<Map<String, dynamic>>? getJsonList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getJsonList,
        [key],
      )) as List<Map<String, dynamic>>?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Set<String> getKeysWithPrefix(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #getKeysWithPrefix,
          [prefix],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  _i6.Future<void> removeKeysWithPrefix(String? prefix) => (super.noSuchMethod(
        Invocation.method(
          #removeKeysWithPrefix,
          [prefix],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i5.StorageStats getStorageStats() => (super.noSuchMethod(
        Invocation.method(
          #getStorageStats,
          [],
        ),
        returnValue: _FakeStorageStats_4(
          this,
          Invocation.method(
            #getStorageStats,
            [],
          ),
        ),
      ) as _i5.StorageStats);

  @override
  _i6.Future<void> appendToFile(
    String? fileName,
    String? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendToFile,
          [
            fileName,
            data,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> fileExists(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #fileExists,
          [fileName],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int?> getFileSize(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [fileName],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<void> renameFile(
    String? oldFileName,
    String? newFileName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameFile,
          [
            oldFileName,
            newFileName,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteFile(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [fileName],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> readFile(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #readFile,
          [fileName],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> writeFile(
    String? fileName,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeFile,
          [
            fileName,
            content,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
