// Mocks generated by Mockito 5.4.6 from annotations
// in lupin_mobile/test/services/audio/audio_cache_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i9;

import 'package:lupin_mobile/core/cache/audio_cache.dart' as _i2;
import 'package:lupin_mobile/core/cache/audio_compression.dart' as _i6;
import 'package:lupin_mobile/core/cache/cache_analytics.dart' as _i4;
import 'package:lupin_mobile/core/cache/cache_policy.dart' as _i11;
import 'package:lupin_mobile/core/cache/eviction_manager.dart' as _i5;
import 'package:lupin_mobile/core/cache/voice_recording_cache.dart' as _i3;
import 'package:lupin_mobile/shared/models/models.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioCacheStats_0 extends _i1.SmartFake
    implements _i2.AudioCacheStats {
  _FakeAudioCacheStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoiceRecordingCacheStats_1 extends _i1.SmartFake
    implements _i3.VoiceRecordingCacheStats {
  _FakeVoiceRecordingCacheStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheAnalyticsData_2 extends _i1.SmartFake
    implements _i4.CacheAnalyticsData {
  _FakeCacheAnalyticsData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEvictionResult_3 extends _i1.SmartFake
    implements _i5.EvictionResult {
  _FakeEvictionResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompressionSettings_4 extends _i1.SmartFake
    implements _i6.CompressionSettings {
  _FakeCompressionSettings_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompressionStatistics_5 extends _i1.SmartFake
    implements _i6.CompressionStatistics {
  _FakeCompressionStatistics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioCache extends _i1.Mock implements _i2.AudioCache {
  MockAudioCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.AudioCacheEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i7.Stream<_i2.AudioCacheEvent>.empty(),
      ) as _i7.Stream<_i2.AudioCacheEvent>);

  @override
  _i7.Future<void> cacheAudioForText(
    String? text,
    String? provider,
    List<_i8.AudioChunk>? chunks,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAudioForText,
          [
            text,
            provider,
            chunks,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.AudioChunk>?> getCachedAudioForText(
    String? text,
    String? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAudioForText,
          [
            text,
            provider,
          ],
        ),
        returnValue: _i7.Future<List<_i8.AudioChunk>?>.value(),
      ) as _i7.Future<List<_i8.AudioChunk>?>);

  @override
  _i7.Future<void> precacheCommonPhrases(
    List<String>? phrases,
    String? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #precacheCommonPhrases,
          [
            phrases,
            provider,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.AudioCacheStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue:
            _i7.Future<_i2.AudioCacheStats>.value(_FakeAudioCacheStats_0(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i7.Future<_i2.AudioCacheStats>);

  @override
  _i7.Future<void> clearProviderCache(String? provider) => (super.noSuchMethod(
        Invocation.method(
          #clearProviderCache,
          [provider],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> getCachedPhrases(String? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedPhrases,
          [provider],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VoiceRecordingCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceRecordingCache extends _i1.Mock
    implements _i3.VoiceRecordingCache {
  MockVoiceRecordingCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i3.VoiceRecordingCacheEvent> get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _i7.Stream<_i3.VoiceRecordingCacheEvent>.empty(),
      ) as _i7.Stream<_i3.VoiceRecordingCacheEvent>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheRecording({
    required _i8.VoiceInput? voiceInput,
    required _i9.Uint8List? audioData,
    String? transcription,
    bool? compressed = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheRecording,
          [],
          {
            #voiceInput: voiceInput,
            #audioData: audioData,
            #transcription: transcription,
            #compressed: compressed,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.VoiceRecordingData?> getRecording(String? recordingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecording,
          [recordingId],
        ),
        returnValue: _i7.Future<_i3.VoiceRecordingData?>.value(),
      ) as _i7.Future<_i3.VoiceRecordingData?>);

  @override
  _i7.Future<_i3.TranscriptionData?> getTranscription(String? recordingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTranscription,
          [recordingId],
        ),
        returnValue: _i7.Future<_i3.TranscriptionData?>.value(),
      ) as _i7.Future<_i3.TranscriptionData?>);

  @override
  _i7.Future<List<_i3.RecordingMetadata>> getRecordingsBySession(
          String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecordingsBySession,
          [sessionId],
        ),
        returnValue: _i7.Future<List<_i3.RecordingMetadata>>.value(
            <_i3.RecordingMetadata>[]),
      ) as _i7.Future<List<_i3.RecordingMetadata>>);

  @override
  _i7.Future<List<_i3.RecordingMetadata>> getRecentRecordings({
    int? limit = 10,
    Duration? within,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentRecordings,
          [],
          {
            #limit: limit,
            #within: within,
          },
        ),
        returnValue: _i7.Future<List<_i3.RecordingMetadata>>.value(
            <_i3.RecordingMetadata>[]),
      ) as _i7.Future<List<_i3.RecordingMetadata>>);

  @override
  _i7.Future<List<_i3.RecordingSearchResult>> searchByTranscription(
    String? query, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchByTranscription,
          [query],
          {#limit: limit},
        ),
        returnValue: _i7.Future<List<_i3.RecordingSearchResult>>.value(
            <_i3.RecordingSearchResult>[]),
      ) as _i7.Future<List<_i3.RecordingSearchResult>>);

  @override
  _i7.Future<_i3.VoiceRecordingCacheStats> getStats() => (super.noSuchMethod(
        Invocation.method(
          #getStats,
          [],
        ),
        returnValue: _i7.Future<_i3.VoiceRecordingCacheStats>.value(
            _FakeVoiceRecordingCacheStats_1(
          this,
          Invocation.method(
            #getStats,
            [],
          ),
        )),
      ) as _i7.Future<_i3.VoiceRecordingCacheStats>);

  @override
  _i7.Future<int> removeOldRecordings(Duration? olderThan) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeOldRecordings,
          [olderThan],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> exportRecordings({
    List<String>? recordingIds,
    bool? includeAudio = true,
    bool? includeTranscriptions = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportRecordings,
          [],
          {
            #recordingIds: recordingIds,
            #includeAudio: includeAudio,
            #includeTranscriptions: includeTranscriptions,
          },
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportRecordings,
            [],
            {
              #recordingIds: recordingIds,
              #includeAudio: includeAudio,
              #includeTranscriptions: includeTranscriptions,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CacheAnalytics].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheAnalytics extends _i1.Mock implements _i4.CacheAnalytics {
  MockCacheAnalytics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i4.AnalyticsEvent> get analyticsStream => (super.noSuchMethod(
        Invocation.getter(#analyticsStream),
        returnValue: _i7.Stream<_i4.AnalyticsEvent>.empty(),
      ) as _i7.Stream<_i4.AnalyticsEvent>);

  @override
  double get overallHitRate => (super.noSuchMethod(
        Invocation.getter(#overallHitRate),
        returnValue: 0.0,
      ) as double);

  @override
  double get compressionRatio => (super.noSuchMethod(
        Invocation.getter(#compressionRatio),
        returnValue: 0.0,
      ) as double);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void recordCacheStore({
    required String? type,
    required String? provider,
    required int? sizeBytes,
    int? compressedSizeBytes,
    Duration? latency,
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordCacheStore,
          [],
          {
            #type: type,
            #provider: provider,
            #sizeBytes: sizeBytes,
            #compressedSizeBytes: compressedSizeBytes,
            #latency: latency,
            #metadata: metadata,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordCacheHit({
    required String? type,
    required String? provider,
    int? sizeBytes,
    Duration? latency,
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordCacheHit,
          [],
          {
            #type: type,
            #provider: provider,
            #sizeBytes: sizeBytes,
            #latency: latency,
            #metadata: metadata,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordCacheMiss({
    required String? type,
    required String? provider,
    Duration? latency,
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordCacheMiss,
          [],
          {
            #type: type,
            #provider: provider,
            #latency: latency,
            #metadata: metadata,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordEviction({
    required String? reason,
    required int? itemCount,
    required int? bytesFreed,
    Duration? latency,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #recordEviction,
          [],
          {
            #reason: reason,
            #itemCount: itemCount,
            #bytesFreed: bytesFreed,
            #latency: latency,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.CacheAnalyticsData> getAnalytics() => (super.noSuchMethod(
        Invocation.method(
          #getAnalytics,
          [],
        ),
        returnValue:
            _i7.Future<_i4.CacheAnalyticsData>.value(_FakeCacheAnalyticsData_2(
          this,
          Invocation.method(
            #getAnalytics,
            [],
          ),
        )),
      ) as _i7.Future<_i4.CacheAnalyticsData>);

  @override
  double getProviderHitRate(String? provider) => (super.noSuchMethod(
        Invocation.method(
          #getProviderHitRate,
          [provider],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double getTypeHitRate(String? type) => (super.noSuchMethod(
        Invocation.method(
          #getTypeHitRate,
          [type],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  Map<String, _i4.LatencyStats> getLatencyStats() => (super.noSuchMethod(
        Invocation.method(
          #getLatencyStats,
          [],
        ),
        returnValue: <String, _i4.LatencyStats>{},
      ) as Map<String, _i4.LatencyStats>);

  @override
  void updateMetrics() => super.noSuchMethod(
        Invocation.method(
          #updateMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetPeriod() => super.noSuchMethod(
        Invocation.method(
          #resetPeriod,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<String> exportReport({
    DateTime? startDate,
    DateTime? endDate,
    String? format = 'json',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportReport,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #format: format,
          },
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportReport,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #format: format,
            },
          ),
        )),
      ) as _i7.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [EvictionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvictionManager extends _i1.Mock implements _i5.EvictionManager {
  MockEvictionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i5.EvictionEvent> get evictionEvents => (super.noSuchMethod(
        Invocation.getter(#evictionEvents),
        returnValue: _i7.Stream<_i5.EvictionEvent>.empty(),
      ) as _i7.Stream<_i5.EvictionEvent>);

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.EvictionResult> runEviction({
    required int? currentSizeBytes,
    required int? maxSizeBytes,
    _i11.CacheEvictionStrategy? strategy,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runEviction,
          [],
          {
            #currentSizeBytes: currentSizeBytes,
            #maxSizeBytes: maxSizeBytes,
            #strategy: strategy,
            #force: force,
          },
        ),
        returnValue: _i7.Future<_i5.EvictionResult>.value(_FakeEvictionResult_3(
          this,
          Invocation.method(
            #runEviction,
            [],
            {
              #currentSizeBytes: currentSizeBytes,
              #maxSizeBytes: maxSizeBytes,
              #strategy: strategy,
              #force: force,
            },
          ),
        )),
      ) as _i7.Future<_i5.EvictionResult>);

  @override
  _i7.Future<_i5.EvictionResult> smartEviction({
    required int? currentSizeBytes,
    required int? maxSizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #smartEviction,
          [],
          {
            #currentSizeBytes: currentSizeBytes,
            #maxSizeBytes: maxSizeBytes,
          },
        ),
        returnValue: _i7.Future<_i5.EvictionResult>.value(_FakeEvictionResult_3(
          this,
          Invocation.method(
            #smartEviction,
            [],
            {
              #currentSizeBytes: currentSizeBytes,
              #maxSizeBytes: maxSizeBytes,
            },
          ),
        )),
      ) as _i7.Future<_i5.EvictionResult>);

  @override
  _i7.Future<_i5.EvictionResult> emergencyEviction({
    required int? currentSizeBytes,
    required int? maxSizeBytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emergencyEviction,
          [],
          {
            #currentSizeBytes: currentSizeBytes,
            #maxSizeBytes: maxSizeBytes,
          },
        ),
        returnValue: _i7.Future<_i5.EvictionResult>.value(_FakeEvictionResult_3(
          this,
          Invocation.method(
            #emergencyEviction,
            [],
            {
              #currentSizeBytes: currentSizeBytes,
              #maxSizeBytes: maxSizeBytes,
            },
          ),
        )),
      ) as _i7.Future<_i5.EvictionResult>);

  @override
  _i7.Future<_i5.EvictionResult> cleanupExpired() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpired,
          [],
        ),
        returnValue: _i7.Future<_i5.EvictionResult>.value(_FakeEvictionResult_3(
          this,
          Invocation.method(
            #cleanupExpired,
            [],
          ),
        )),
      ) as _i7.Future<_i5.EvictionResult>);

  @override
  _i7.Future<List<_i5.EvictionRecommendation>> getEvictionRecommendations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvictionRecommendations,
          [],
        ),
        returnValue: _i7.Future<List<_i5.EvictionRecommendation>>.value(
            <_i5.EvictionRecommendation>[]),
      ) as _i7.Future<List<_i5.EvictionRecommendation>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AudioCompression].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioCompression extends _i1.Mock implements _i6.AudioCompression {
  MockAudioCompression() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i9.Uint8List> compress(
    _i9.Uint8List? data, {
    required String? format,
    double? quality,
    int? targetBitrate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compress,
          [data],
          {
            #format: format,
            #quality: quality,
            #targetBitrate: targetBitrate,
          },
        ),
        returnValue: _i7.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i7.Future<_i9.Uint8List>);

  @override
  _i7.Future<_i9.Uint8List> decompress(
    _i9.Uint8List? data, {
    required String? format,
    _i6.CompressionMetadata? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decompress,
          [data],
          {
            #format: format,
            #metadata: metadata,
          },
        ),
        returnValue: _i7.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i7.Future<_i9.Uint8List>);

  @override
  double getCompressionRatio(
    _i9.Uint8List? originalData,
    _i9.Uint8List? compressedData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompressionRatio,
          [
            originalData,
            compressedData,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.CompressionSettings getOptimalSettings({
    required String? format,
    required int? sampleRate,
    required int? bitDepth,
    required Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOptimalSettings,
          [],
          {
            #format: format,
            #sampleRate: sampleRate,
            #bitDepth: bitDepth,
            #duration: duration,
          },
        ),
        returnValue: _FakeCompressionSettings_4(
          this,
          Invocation.method(
            #getOptimalSettings,
            [],
            {
              #format: format,
              #sampleRate: sampleRate,
              #bitDepth: bitDepth,
              #duration: duration,
            },
          ),
        ),
      ) as _i6.CompressionSettings);

  @override
  int estimateCompressedSize(
    int? originalSize,
    String? format, {
    double? quality,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateCompressedSize,
          [
            originalSize,
            format,
          ],
          {#quality: quality},
        ),
        returnValue: 0,
      ) as int);

  @override
  _i6.CompressionStatistics getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _FakeCompressionStatistics_5(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        ),
      ) as _i6.CompressionStatistics);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetStatistics() => super.noSuchMethod(
        Invocation.method(
          #resetStatistics,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
