import 'dart:async';
import '../../shared/models/models.dart';
import 'base_repository.dart';

/// Repository interface for AudioChunk entities with specialized audio operations.
/// 
/// Provides comprehensive audio chunk management with caching, provider-specific
/// operations, and performance optimization for TTS audio data.
abstract class AudioRepository extends BaseRepository<AudioChunk, String> {
  /// Retrieves audio chunks filtered by chunk type.
  /// 
  /// Requires:
  ///   - type must be a valid AudioChunkType value
  /// 
  /// Ensures:
  ///   - Returns all chunks matching the specified type
  ///   - Results are ordered by creation time
  ///   - No side effects on storage
  /// 
  /// Raises:
  ///   - ArgumentError if type is invalid
  ///   - RepositoryException if storage query fails
  Future<List<AudioChunk>> findByType(AudioChunkType type);
  
  /// Retrieves audio chunks from a specific TTS provider.
  /// 
  /// Requires:
  ///   - provider must be a valid TTS provider identifier
  /// 
  /// Ensures:
  ///   - Returns all chunks generated by the specified provider
  ///   - Results include provider-specific metadata
  ///   - Chunks are ordered by generation time
  /// 
  /// Raises:
  ///   - ArgumentError if provider is invalid
  ///   - RepositoryException if storage query fails
  Future<List<AudioChunk>> findByProvider(String provider);
  
  /// Retrieves audio chunks associated with specific text.
  /// 
  /// Requires:
  ///   - text must be non-empty
  /// 
  /// Ensures:
  ///   - Returns all chunks generated from the specified text
  ///   - Results may include chunks from different providers
  ///   - Chunks are ordered by generation time
  /// 
  /// Raises:
  ///   - ArgumentError if text is empty
  ///   - RepositoryException if storage query fails
  Future<List<AudioChunk>> findByText(String text);
  
  /// Retrieves audio chunks for a complete sequence.
  /// 
  /// Requires:
  ///   - textHash must be a valid hash identifier
  ///   - totalChunks (if provided) must be positive
  /// 
  /// Ensures:
  ///   - Returns complete sequence of chunks in order
  ///   - Verifies sequence completeness if totalChunks provided
  ///   - Chunks are ordered by sequence number
  /// 
  /// Raises:
  ///   - ArgumentError if textHash is invalid
  ///   - IncompleteSequenceException if sequence is incomplete
  ///   - RepositoryException if storage query fails
  Future<List<AudioChunk>> findBySequence(String textHash, {int? totalChunks});
  
  /// Retrieves cached audio chunks for specific text and provider.
  /// 
  /// Requires:
  ///   - text must be non-empty
  ///   - provider must be a valid TTS provider identifier
  /// 
  /// Ensures:
  ///   - Returns cached chunks if available and valid
  ///   - Returns null if no cached audio exists
  ///   - Chunks are complete and playable sequence
  /// 
  /// Raises:
  ///   - ArgumentError if text or provider is invalid
  ///   - RepositoryException if cache access fails
  Future<List<AudioChunk>?> getCachedAudio(String text, String provider);
  
  /// Stores audio chunks in the cache for future retrieval.
  /// 
  /// Requires:
  ///   - chunks must be non-empty list of valid AudioChunk instances
  ///   - chunks must belong to the same text and provider
  ///   - chunks must form a complete sequence
  /// 
  /// Ensures:
  ///   - All chunks are stored in the cache
  ///   - Cache metadata is updated
  ///   - Existing cache for same text/provider is replaced
  /// 
  /// Raises:
  ///   - ArgumentError if chunks are invalid or incomplete
  ///   - CacheFullException if insufficient cache space
  ///   - RepositoryException if storage operation fails
  Future<void> cacheAudio(List<AudioChunk> chunks);
  
  /// Retrieves comprehensive audio cache performance statistics.
  /// 
  /// Requires:
  ///   - Cache system must be accessible
  /// 
  /// Ensures:
  ///   - Returns current cache metrics and utilization
  ///   - Includes provider and type breakdowns
  ///   - Statistics reflect real-time cache state
  /// 
  /// Raises:
  ///   - RepositoryException if cache access fails
  Future<AudioCacheStats> getCacheStats();
  
  /// Removes cached audio older than specified duration.
  /// 
  /// Requires:
  ///   - olderThan (if provided) must be a positive duration
  /// 
  /// Ensures:
  ///   - Old cache entries are permanently removed
  ///   - Returns count of removed chunks
  ///   - Cache size is reduced appropriately
  /// 
  /// Raises:
  ///   - ArgumentError if olderThan is invalid
  ///   - RepositoryException if cleanup operation fails
  Future<int> cleanupOldCache({Duration? olderThan});
  
  /// Returns total cache size in bytes.
  /// 
  /// Requires:
  ///   - Cache system must be accessible
  /// 
  /// Ensures:
  ///   - Returns accurate total size of all cached audio
  ///   - Size includes all audio data and metadata
  ///   - Calculation is efficient and fast
  /// 
  /// Raises:
  ///   - RepositoryException if cache access fails
  Future<int> getCacheSize();
  
  /// Clears all cached audio from specific provider.
  /// 
  /// Requires:
  ///   - provider must be a valid TTS provider identifier
  /// 
  /// Ensures:
  ///   - All audio chunks from provider are removed
  ///   - Cache size is reduced accordingly
  ///   - Other providers' cache remains intact
  /// 
  /// Raises:
  ///   - ArgumentError if provider is invalid
  ///   - RepositoryException if cache operation fails
  Future<void> clearCacheByProvider(String provider);
  
  /// Clears all cached audio of specific chunk type.
  /// 
  /// Requires:
  ///   - type must be a valid AudioChunkType value
  /// 
  /// Ensures:
  ///   - All chunks of specified type are removed
  ///   - Cache size is reduced accordingly
  ///   - Other chunk types remain intact
  /// 
  /// Raises:
  ///   - ArgumentError if type is invalid
  ///   - RepositoryException if cache operation fails
  Future<void> clearCacheByType(AudioChunkType type);
  
  /// Retrieves audio chunks filtered by processing status.
  /// 
  /// Requires:
  ///   - status must be a valid AudioChunkStatus value
  /// 
  /// Ensures:
  ///   - Returns all chunks with specified status
  ///   - Results are ordered by status change time
  ///   - Status filtering is accurate and current
  /// 
  /// Raises:
  ///   - ArgumentError if status is invalid
  ///   - RepositoryException if storage query fails
  Future<List<AudioChunk>> findByStatus(AudioChunkStatus status);
  
  /// Updates the processing status of a specific audio chunk.
  /// 
  /// Requires:
  ///   - chunkId must be a valid identifier of existing chunk
  ///   - status must be a valid AudioChunkStatus value
  /// 
  /// Ensures:
  ///   - Chunk status is updated in storage
  ///   - Returns updated chunk with new status
  ///   - Status change timestamp is recorded
  /// 
  /// Raises:
  ///   - ArgumentError if chunkId or status is invalid
  ///   - EntityNotFoundException if chunk does not exist
  ///   - RepositoryException if update operation fails
  Future<AudioChunk> updateStatus(String chunkId, AudioChunkStatus status);
  
  /// Retrieves most frequently accessed cached texts.
  /// 
  /// Requires:
  ///   - limit must be positive and reasonable (< 1000)
  /// 
  /// Ensures:
  ///   - Returns text strings ordered by cache access frequency
  ///   - Results include only cached texts with audio
  ///   - Frequency data is accurate and current
  /// 
  /// Raises:
  ///   - ArgumentError if limit is invalid
  ///   - RepositoryException if cache analysis fails
  Future<List<String>> getMostCachedTexts({int limit = 10});
  
  /// Performs comprehensive cache optimization.
  /// 
  /// Requires:
  ///   - Cache system must be accessible
  ///   - Sufficient system resources for optimization
  /// 
  /// Ensures:
  ///   - Duplicate chunks are removed
  ///   - Cache fragmentation is reduced
  ///   - Storage efficiency is improved
  ///   - Cache performance is enhanced
  /// 
  /// Raises:
  ///   - RepositoryException if optimization process fails
  Future<void> optimizeCache();
  
  /// Exports complete cache data for backup or migration.
  /// 
  /// Requires:
  ///   - Cache system must be accessible
  ///   - Sufficient memory for cache serialization
  /// 
  /// Ensures:
  ///   - Returns complete cache data in serializable format
  ///   - Includes all audio chunks and metadata
  ///   - Export format is compatible with importCache
  /// 
  /// Raises:
  ///   - MemoryException if cache is too large to serialize
  ///   - RepositoryException if cache access fails
  Future<Map<String, dynamic>> exportCache();
  
  /// Imports cache data from backup or migration.
  /// 
  /// Requires:
  ///   - cacheData must be valid export format
  ///   - Cache system must be accessible
  ///   - Sufficient storage space for imported data
  /// 
  /// Ensures:
  ///   - Cache data is restored from backup
  ///   - Existing cache is replaced with imported data
  ///   - All audio chunks are validated and accessible
  /// 
  /// Raises:
  ///   - ValidationException if cacheData format is invalid
  ///   - StorageException if insufficient space
  ///   - RepositoryException if import operation fails
  Future<void> importCache(Map<String, dynamic> cacheData);
}

/// Audio cache statistics
class AudioCacheStats {
  final int totalChunks;
  final int cacheHits;
  final int cacheMisses;
  final int totalSizeBytes;
  final int maxSizeBytes;
  final Map<String, int> chunksByProvider;
  final Map<String, int> chunksByType;
  final Map<String, double> averageChunkSize;
  final Duration oldestCacheEntry;
  final Duration newestCacheEntry;

  const AudioCacheStats({
    required this.totalChunks,
    required this.cacheHits,
    required this.cacheMisses,
    required this.totalSizeBytes,
    required this.maxSizeBytes,
    this.chunksByProvider = const {},
    this.chunksByType = const {},
    this.averageChunkSize = const {},
    required this.oldestCacheEntry,
    required this.newestCacheEntry,
  });

  double get hitRate => 
      (cacheHits + cacheMisses) > 0 ? cacheHits / (cacheHits + cacheMisses) : 0.0;

  double get cacheUtilization => 
      maxSizeBytes > 0 ? totalSizeBytes / maxSizeBytes : 0.0;

  Map<String, dynamic> toJson() {
    return {
      'total_chunks': totalChunks,
      'cache_hits': cacheHits,
      'cache_misses': cacheMisses,
      'total_size_bytes': totalSizeBytes,
      'max_size_bytes': maxSizeBytes,
      'hit_rate': hitRate,
      'cache_utilization': cacheUtilization,
      'chunks_by_provider': chunksByProvider,
      'chunks_by_type': chunksByType,
      'average_chunk_size': averageChunkSize,
      'oldest_cache_entry': oldestCacheEntry.inMilliseconds,
      'newest_cache_entry': newestCacheEntry.inMilliseconds,
    };
  }
}